name: Check

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org/
          scope: '@kapeta'
          cache: 'npm'
      - run: npm install
      - run: npm run build
      - run: npm run test
  bootstrap:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org/
          cache: 'npm'
      - run: npm install
        working-directory: ./test/resources/examples/todo
      # TODO: test step!?
      - run: npm run --if-present test
        working-directory: ./test/resources/examples/todo
      - run: npm run lint
        working-directory: ./test/resources/examples/todo
      - run: npm run build
        working-directory: ./test/resources/examples/todo
